- .circleci/config.yml
- bitwarden/chart/.helmignore
- bitwarden/chart/Chart.yaml
- bitwarden/chart/templates/deployment.yaml
- bitwarden/chart/templates/ingress.yaml
- bitwarden/chart/templates/service.yaml
- bitwarden/chart/values.yml
- bitwarden/init.sh
- bitwarden/values.yml
- init_cluster.sh
This PR adds bitwarden_rs for all the password-managing goodness
> Add bitwarden_rs

- docker/ghost-s3/Dockerfile
@pawalt if you want to try and see if this works, i think this might fail earlier, though.
> try content instead of content-orig

- README.md
- init_cluster.sh
- phpmyadmin/README.md
- phpmyadmin/init.sh
- phpmyadmin/values.yaml
This PR adds a phpMyAdmin helm chart. Additionally, it modifies `init_cluster.sh` to set up the Penn Labs helm repository.
> Add phpMyAdmin

- tf/README.md
- tf/ghost.tf
- tf/main.tf
- tf/outputs.tf
- tf/provider.tf
- tf/vault.tf
This PR splits the terraform files and adds a README
> Split terraform files

- .github/workflows/pg-s3-backup.yaml
- docker/README.md
- docker/pg-s3-backup/Dockerfile
- docker/pg-s3-backup/README.md
- docker/pg-s3-backup/backup
This PR:
* Adds a new docker image that will backup all the databases within a PostgreSQL cluster to an S3 bucket
* Adds a GitHub action to publish that image
> PostgreSQL S3 Backup Docker Image

- terraform/base/main.tf
- terraform/base/provider.tf
This bumps up our database size
> Upgrade prod db + cluster

- grafana-dashboards/pod-alerting-dashboard.json
This PR adds CPU alerts to grafana
> Add CPU alerts

- terraform/base/main.tf
This PR sets up a database for fyh
> Add first-year-hub database

- docker/pg-s3-backup/README.md
- docker/pg-s3-backup/backup
> Update pg backup for RDS

- docker/team-sync/Pipfile
- docker/team-sync/Pipfile.lock
- docker/team-sync/sync/modules/platform.py
- docker/team-sync/sync/modules/vault.py
- docker/team-sync/sync/sync.py
This PR modifies team-sync to generate a dictionary of pennkeys to products that those users should have admin access to and then makes a POST request to platform.
See pennlabs/platform#87
[ch3268]
> Sync product admin from GitHub

- cdk/kraken/CHANGELOG.md
- cdk/kraken/src/pypi.ts
- cdk/kraken/test/__snapshots__/pypi.test.ts.snap
This PR modifies the PyPI workflow to fully use poetry for building and publishing packages
> [Kraken] Modify PyPI publish to use poetry

- docker/team-sync/sync/modules/bitwarden.py
This PR modifies our team sync image to stabilize bitwarden syncing. Previously our CronJob running this image would error out frequently, with these changes the image rarely (if ever) doesn't work. I believe introducing the 30-second wait as well as ensuring the second totp code is generated just before making the POST request with it solved the problem.
> [Team Sync] Fix bitwarden syncing

- docker/django-base/Dockerfile
> :arrow_up: Upgrade python image and remove mysql dependency

- terraform/eks.tf
- terraform/helm/aws-node-termination-handler.yaml
- terraform/helm/cert-manager.yaml
- terraform/helm/grafana.yaml
- terraform/helm/prometheus.yaml
- terraform/helm/traefik.yaml
- terraform/helm/weave.yaml
- terraform/modules/base_cluster/vault-secret-sync.tf
This PR migrates the cluster to use weave (to get around pod density limits) as well as adding image pull secrets to most resources in the cluster.
> [Terraform] Weave + Image Pull Secrets

- cdk/kittyhawk/README.md
- cdk/kittyhawk/src/chart.ts
By default, a `PennLabsChart` assumes the default name of `"pennlabs"`. The documentation is also updated to reflect this change.
> [Kittyhawk] Make name of PennLabsChart

- cdk/kittyhawk/.projenrc.js
- cdk/kittyhawk/package.json
- cdk/kittyhawk/src/imports/k8s.ts
> Update EKS from v1.21 to v1.22

- docker/shibboleth-sp-nginx/Dockerfile
Reverts pennlabs/infrastructure#183
> Revert "Bump shibboleth-sp-nginx to Debian 12 (again)"

- cdk/kittyhawk/LICENSE
- cdk/kittyhawk/src/application/redis.ts
- cdk/kittyhawk/test/application/__snapshots__/redis.test.ts.snap
- cdk/kittyhawk/test/deployment.test.ts
See my write-up here:
https://www.notion.so/pennlabs/Why-Redis-Persistence-Didn-t-Work-f82f9e9a62cf4ebc94d6ae9cf0ced990?pvs=4
> Fix Redis Persistence (for real)

- docker/waypoint/src/main.py
- docker/waypoint/src/waypoint_client.py
No functional changes but will decrease the size of the diffs for future PRs.
> Waypoint: Lint

- docker/waypoint/src/main.py
- docker/waypoint/src/waypoint_client.py
`init_product` calls `clone_product`, so `clone_product` is called twice in `clone_and_init_products`. This PR removes the extra `clone_product` call in `clone_and_init_products`
> Waypoint: Refactor clone and init products
