pennlabs/infrastructure

terraform/base/db-backup.tf, terraform/base/helm-production/db-backup.yaml
This PR creates two cronjobs to backup our production and infrastructure databases to AWS daily. Note that I'm intentionally not including the creation of the IAM user or vault secrets in the PR as these will be handled later in our planned S3 terraform module
=> Database backup cronjobs

.github/workflows/pg-s3-backup.yaml, docker/pg-s3-backup/backup
This PR modifies the backup docker image to ensure that the backups for both the production and infrastructure databases end up in the same folder. Previously they would differ by ~1 second when starting which would result in different folders being created.
=> Modify backup names

atlantis.yaml, terraform/README.md, terraform/base/README.md, terraform/base/atlantis.tf, terraform/base/helm-production/atlantis.yaml
This PR configures Atlantis to manage our terraform configs. Right now, a shadow version of Atlantis is running on `sandbox` which will be used to merge this PR and apply the new terraform configs.
We need to wait until a PR I made in the Atlantis helm chart is merged before we can merge this PR.
After merging this PR, the Atlantis GitHub app needs to be updated to change all references from atlantis-sandbox.pennlabs.org to atlantis.pennlabs.org
=> Add Atlantis

.gitmodules, atlantis.yaml, grafana-dashboards/README.md, grafana-dashboards/cert-manager.json, terraform/base/helm-production/atlantis.yaml, terraform/base/helm-production/prometheus.yaml, terraform/base/helm-production/traefik.yaml, terraform/base/helm-sandbox/prometheus.yaml, terraform/base/helm-sandbox/traefik.yaml, terraform/chronos/helm/prometheus.yaml, terraform/chronos/helm/traefik.yaml, terraform/chronos/vault.tf, terraform/modules/base_cluster/traefik.tf
This PR:
* modifies our Prometheus and traefik configuration so that Prometheus scrapes each traefik pod individually instead of just the service.
* creates a cert-manager grafana dashboard that will be configured in a separate commit
* Migrates to using the [official hosted vault helm chart](https://github.com/hashicorp/vault-helm) (Note that we were already running vault 0.5.0 in our cluster even though the version said 0.4.0)
* Fixes our atlantis config file
=> Prometheus + Traefik Updates

atlantis.yaml, terraform/base/helm-production/atlantis.yaml, terraform/base/provider.tf, terraform/chronos/provider.tf
The PR ensures that a `terraform refresh` is run on chronos any time that changes to base are needed.
This is needed because without this explicit refresh, the kubeconfig stored in chronos would be invalidated after approximately 1 week and running terraform commands for base wouldn't refresh the config.
=> Refresh Chronos on Base Changes

terraform/.terraform.lock.hcl, terraform/README.md, terraform/github.tf, terraform/main.tf, terraform/provider.tf
A new release of the GitHub provider added the ability to manage organization GitHub Actions secrets. This PR configures terraform to create the secrets we need to deploy our products.
=> Manage GitHub org secrets in terraform

terraform/helm/cert-manager.yaml, terraform/iam.tf, terraform/modules/base_cluster/cert-manager.tf, terraform/modules/base_cluster/clusterissuer.yaml, terraform/modules/base_cluster/variables.tf, terraform/modules/domain/README.md, terraform/modules/domain/main.tf, terraform/production-cluster.tf, terraform/route53.tf
This PR modifies our infrastructure so that cert-manager in the cluster directly makes DNS changes in Route53 rather than the weird CNAME redirect we were doing using upenn.club for lets encrypt challenges.
=> [Terraform] Use Route53 directly for LE

cdk/kraken/CHANGELOG.md, cdk/kraken/package.json, cdk/kraken/src/cdk.ts, cdk/kraken/src/deploy.ts, cdk/kraken/src/django.ts, cdk/kraken/src/integration-tests.ts, cdk/kraken/src/pypi.ts, cdk/kraken/src/react.ts, cdk/kraken/test/__snapshots__/pypi.test.ts.snap, cdk/kraken/yarn.lock
This PR:
* Fixes the publish job within the PyPI stack by forcing GH Actions to use bash (this was annoying to find)
* Modifies python versions to be strings (3.10 != 3.1) and removes 3.6 from the defaults since it's almost EOL
* Migrates the project to ts-dedent to conform with cdkactions
=> [Kraken] Fix PyPI Publish Job

docker/django-base/Dockerfile
`libc-dev` needed for `psycopg2`
=> :new: Add libc-dev to django-base

terraform/eks.tf, terraform/helm/aws-node-termination-handler.yaml, terraform/main.tf, terraform/vpc.tf
This PR:
* Moves us over to managed EKS node groups rather than the "self-managed" version through the EKS terraform module
* Grants the `platform` IAM user admin access to the EKS cluster (so it can view details in the web console)
* Expands our VPC so we can put more pods on our EKS nodes (I can't believe I thought 256 IPs per availability zone were enough)
* Switches us to using r5d.large instances for our EKS cluster to save (hopefully) lots of money
Note that the traefik load balancer changed because our entire cluster had to be rebuilt on the new VPC subnets
=> [Terraform] Expand VPC + Managed EKS Nodes

terraform/.terraform.lock.hcl, terraform/README.md, terraform/backend.tf, terraform/eks.tf, terraform/helm/vault-secret-sync.yaml, terraform/main.tf, terraform/modules/vault/README.md, terraform/modules/vault/cert-manager.tf, terraform/modules/vault/variables.tf, terraform/variables.tf, terraform/vault.tf
This PR:
* Updates the EKS terraform module (which required us to delete and rebuild the cluster again)
* Creates a docker-pull-secret with a DockerHub token so we don't run into pull limits
* Removes all references to Cloudflare which was previously used by cert-manager (but we've since migrated to route53)
* Does a better job bootstrapping the cluster by running a few `kubectl` commands on cluster creation
* Updates our backend S3 module
=> [Terraform] Eliminate more Tech Debt

cdk/kittyhawk/.projen/tasks.json, cdk/kittyhawk/.projenrc.js
Currently, running `yarn test` for kittyhawk update snapshots, which should not be done. This PR fixes that by:
- Adding in a patch in the `.projenrc.js` file that edits the tasks
- Fixing existing snapshots so that they are up to date
=> [Kittyhawk] Fix yarn test: no update snapshot during test

cdk/kraken/CHANGELOG.md, cdk/kraken/src/cdk.ts, cdk/kraken/test/__snapshots__/cdk.test.ts.snap
Previously, the "Publish to npm" step does not check if the version in `package.json` has been updated before attempting to publish. 
While this is fixed by the npm erroring out, this behavior should be fixed and the "Publish to npm" step should not run if the version has not changed. 
```
error Couldn't publish package: "https://registry.yarnpkg.com/@pennlabs%2fkittyhawk: You cannot publish over the previously published versions: 1.1.0."
```
This PR adds in an extra check for whether the package version number has been updated compared to the current version number on npm. 
Example generated YAML:
<details>
<summary>Click to expand!</summary>
```yaml
name: Publish kraken
on:
push:
paths:
- cdk/kraken/**
jobs:
publish:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: …
```
=> [Kraken] Fix npm publish bug: check if version has updated

terraform/eks.tf, terraform/main.tf
This PR scales up the number of nodes (and adds the number of replicas for traefik).
**Wait, aren't we already at 5 nodes?**
Currently, we already scaled up to 5 nodes in AWS via console. However, when we tf apply again, the number of nodes would go back to 3 nodes (I don't know if it _actually_ becomes 3 nodes, but the min/max all get moved back from 2/5 to 3/3). This is pretty sus behavior.
Originally, I planned to delete the `k8s_cluster_size local` because the [desired_size is unsupported](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md#why-are-there-no-changes-when-a-node-groups-desired_size-is-modified). However, the local is still used for the `min_size` & `max_size`, as well as the replicas field for traefik. 
**Alternative solution:** maybe can …
=> [Terraform] Remove desired_size config, scale up k8s_cluster_size local

terraform/rds.tf
Previously, to handle the Clubs outage, we ran a cronjob in the background to kill-off any hanging queries > 60s. To prevent such measures in the future, we will shorten the timeout limits for AWS RDS:
Original (Default Values)
- create - (Default 40m)
- update - (Default 80m) 
- delete - (Default 60m)
New Values
- create - (2m)
- update - (4m) 
- delete - (3m)
=> Shorten AWS RDS Timeouts

docker/shibboleth-sp-nginx/Dockerfile
Root problem: the [platform backend Docker image](https://github.com/pennlabs/platform/blob/a92701f1b88c33e3536329344e9a93e008d1b0da/backend/Dockerfile) is failing to build. Pipenv is failing to lock with a bunch of messages about `Requires-Python >=3.8` we THINK due to python 3.7 no longer being supported (support ended on June 27, 2023). So we want to bump platform backend to python 3.11.
To do this, we want to bump the Debian version of the `shibboleth-sp-nginx` Docker image to Debian 12 (bookworm) which comes with 3.11 so that in the platform backend image (which [extends](https://github.com/pennlabs/platform/blob/a92701f1b88c33e3536329344e9a93e008d1b0da/backend/Dockerfile#L1) `shibboleth-sp-nginx`) we can easily install `python3.11-dev` without needing to build python from scratch …
=> Bump shibboleth-sp-nginx to Debian 12

docker/shibboleth-sp-nginx/Dockerfile
Reverts pennlabs/infrastructure#181
=> Revert "Bump shibboleth-sp-nginx to Debian 12"

docker/shibboleth-sp-nginx/Dockerfile
Second time is the charm... this PR fixes nondeterminism that caused the shibboleth-sp-nginx build to fail, but ONLY the first time you build it (future builds succeeded due to caching or something, which is why I didn't catch this locally the first time).
=> Bump shibboleth-sp-nginx to Debian 12 (again)

docker/django-base/Dockerfile
If `/opt/poetry/bin` is prepended to PATH in the Django base image, then all packages are installed to this directory when using the system flag regardless of whether the project is using pipenv or poetry. This would be a breaking change and should preferably be set within the product's Dockerfile instead of the base.
=> Remove poetry directory from Django Base PATH

terraform/modules/base_cluster/redis.tf
Courses backend was having issues with redis connectivity, turns out that redis base image has protected mode enabled by default. Fixed redis config map to disable protected mode!
=> Disable Redis Protected Mode

.github/workflows/cdkactions_docker-waypoint.yaml
PRs for Waypoint result in actual changes to pennlabs/waypoint:latest on Docker Hub because the current GH actions don't check to see if we're pushing to master. This PR will build and cache the Docker image but will only actually push to Docker Hub if we're on master.
=> Waypoint: Don't push to dockerhub unless on master

docker/waypoint/src/waypoint_client.py
`waypoint-client start` checks to see if the waypoint image is available locally, which fails if the docker daemon is not running. However, this is not very clear from the error output:
```bash
waypoint-client start
Traceback (most recent call last):
File "src/waypoint_client.py", line 254, in <module>
File "src/waypoint_client.py", line 245, in main
File "src/waypoint_client.py", line 108, in start
File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['docker', 'images', '-q', 'pennlabs/waypoint']' returned non-zero exit status 1.
[PYI-69035:ERROR] Failed to execute script 'waypoint_client' due to unhandled exception!
```
This PR includes the error output of the `docker images` command, which could provide a hint to the user as to why the command is failing. New …
=> Waypoint: Print more descriptive error message when Docker isn't running

docker/pg-s3-backup/Dockerfile
Updated to `bookworm-slim` from `buster-slim`
Updated to AWS CLI to `2.27.26` from `2.0.27`
=> Fix pg-backup to work with our pg version

docker/waypoint/Dockerfile, docker/waypoint/src/main.py, docker/waypoint/waypoint-bashrc, docker/waypoint/waypoint-init
Use `pyproject.toml` and `uv.lock` to install backend dependencies with uv. Previously, we had a hacky workaround where we generated a requirements.txt from a Pipfile and then used uv's legacy commands.
The products that haven't been fully migrated to uv are currently commented out (courses, mobile, platform as of now). We should ensure that they are fully migrated within the next week.
=> Use uv only for waypoint backend installation

.github/cdk/main.ts, .github/workflows/cdkactions_docker-django-base.yaml, cdk/kraken/src/django.ts, cdk/kraken/test/__snapshots__/custom.test.ts.snap, cdk/kraken/test/__snapshots__/django-project.test.ts.snap, cdk/kraken/test/__snapshots__/django.test.ts.snap, cdk/kraken/test/__snapshots__/labs-application.test.ts.snap, docker/django-base/Dockerfile, docker/django-base/README.md
Debian 10 (Buster) is end of life. This PR updates the Debian version in django-base to Debian 12 (Bookworm), and updates the Python versions that we support to include only Python 3.10.18 and Python 3.11. All existing products only use Python 3.11, so we can safely stop supporting the old versions.
=> Bump debian version from buster to bookworm

docker/waypoint/install.sh, docker/waypoint/setup.py, docker/waypoint/waypoint-init
Adds support for Penn Courses. We're still missing platform and mobile backend, since they haven't finished migrating to uv.
=> Update hashes and bump to v1.0.4
